// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWSrXJm27h4BTz3Rr0MkXuB84lnz4lb48',
    appId: '1:600104696584:web:8f6140f27891b1db020abd',
    messagingSenderId: '600104696584',
    projectId: 'harag-online-app',
    authDomain: 'harag-online-app.firebaseapp.com',
    storageBucket: 'harag-online-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB77QNe-6qrU7H-u429cwdAbsj3ecmjFOM',
    appId: '1:600104696584:android:97dfe484bc84b388020abd',
    messagingSenderId: '600104696584',
    projectId: 'harag-online-app',
    storageBucket: 'harag-online-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1MRjiLzG7S79SWTS_JWRiOfka5crxsFI',
    appId: '1:600104696584:ios:e3db6db21532cd1b020abd',
    messagingSenderId: '600104696584',
    projectId: 'harag-online-app',
    storageBucket: 'harag-online-app.appspot.com',
    iosClientId: '600104696584-jj53epqesjp969m52hk8p1svshalt2ns.apps.googleusercontent.com',
    iosBundleId: 'com.Amany.harajApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1MRjiLzG7S79SWTS_JWRiOfka5crxsFI',
    appId: '1:600104696584:ios:e3db6db21532cd1b020abd',
    messagingSenderId: '600104696584',
    projectId: 'harag-online-app',
    storageBucket: 'harag-online-app.appspot.com',
    iosClientId: '600104696584-jj53epqesjp969m52hk8p1svshalt2ns.apps.googleusercontent.com',
    iosBundleId: 'com.Amany.harajApp',
  );
}
